# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/brands_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_brands_manager(object):
    def setupUi(self, brands_manager):
        brands_manager.setObjectName("brands_manager")
        brands_manager.resize(1019, 813)
        brands_manager.setStyleSheet("QPushButton{\n"
"  background-color: #D9D9D9;\n"
"  border: none;\n"
"  color: black;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  margin: 4px 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(brands_manager)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_line_edit.sizePolicy().hasHeightForWidth())
        self.name_line_edit.setSizePolicy(sizePolicy)
        self.name_line_edit.setMinimumSize(QtCore.QSize(500, 50))
        self.name_line_edit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.name_line_edit.setObjectName("name_line_edit")
        self.horizontalLayout.addWidget(self.name_line_edit)
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.search_btn.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_btn.sizePolicy().hasHeightForWidth())
        self.create_btn.setSizePolicy(sizePolicy)
        self.create_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.create_btn.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.create_btn.setFont(font)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_4.addWidget(self.create_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.brand_table_view = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brand_table_view.sizePolicy().hasHeightForWidth())
        self.brand_table_view.setSizePolicy(sizePolicy)
        self.brand_table_view.setObjectName("brand_table_view")
        self.verticalLayout.addWidget(self.brand_table_view)
        brands_manager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(brands_manager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 20))
        self.menubar.setObjectName("menubar")
        brands_manager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(brands_manager)
        self.statusbar.setObjectName("statusbar")
        brands_manager.setStatusBar(self.statusbar)

        self.retranslateUi(brands_manager)
        QtCore.QMetaObject.connectSlotsByName(brands_manager)

    def retranslateUi(self, brands_manager):
        _translate = QtCore.QCoreApplication.translate
        brands_manager.setWindowTitle(_translate("brands_manager", "MainWindow"))
        self.name_line_edit.setToolTip(_translate("brands_manager", "Enter brand name"))
        self.name_line_edit.setPlaceholderText(_translate("brands_manager", "Enter brand name"))
        self.search_btn.setText(_translate("brands_manager", "Search"))
        self.create_btn.setText(_translate("brands_manager", "Add new brand"))
import resources_rc
