# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/category_manager_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_categories_manager(object):
    def setupUi(self, categories_manager):
        categories_manager.setObjectName("categories_manager")
        categories_manager.resize(1019, 813)
        categories_manager.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(categories_manager)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_line_edit.sizePolicy().hasHeightForWidth())
        self.name_line_edit.setSizePolicy(sizePolicy)
        self.name_line_edit.setMinimumSize(QtCore.QSize(500, 50))
        self.name_line_edit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.name_line_edit.setObjectName("name_line_edit")
        self.horizontalLayout.addWidget(self.name_line_edit)
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn.sizePolicy().hasHeightForWidth())
        self.search_btn.setSizePolicy(sizePolicy)
        self.search_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.search_btn.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_btn.sizePolicy().hasHeightForWidth())
        self.create_btn.setSizePolicy(sizePolicy)
        self.create_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.create_btn.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.create_btn.setFont(font)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_4.addWidget(self.create_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.category_table_view = QtWidgets.QTableView(self.centralwidget)
        self.category_table_view.setObjectName("category_table_view")
        self.category_table_view.horizontalHeader().setCascadingSectionResizes(True)
        self.category_table_view.horizontalHeader().setSortIndicatorShown(True)
        self.category_table_view.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.category_table_view)
        categories_manager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(categories_manager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 19))
        self.menubar.setObjectName("menubar")
        categories_manager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(categories_manager)
        self.statusbar.setObjectName("statusbar")
        categories_manager.setStatusBar(self.statusbar)

        self.retranslateUi(categories_manager)
        QtCore.QMetaObject.connectSlotsByName(categories_manager)

    def retranslateUi(self, categories_manager):
        _translate = QtCore.QCoreApplication.translate
        categories_manager.setWindowTitle(_translate("categories_manager", "Categories main window"))
        self.name_line_edit.setToolTip(_translate("categories_manager", "Enter brand name"))
        self.name_line_edit.setPlaceholderText(_translate("categories_manager", "Enter category name"))
        self.search_btn.setText(_translate("categories_manager", "Search"))
        self.create_btn.setText(_translate("categories_manager", "Add new Category"))
import resources_rc
