# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/input_field.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_field(object):
    def setupUi(self, input_field):
        input_field.setObjectName("input_field")
        input_field.resize(489, 213)
        self.verticalLayout = QtWidgets.QVBoxLayout(input_field)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(input_field)
        self.name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.name_label.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.input_line_edit = ValidatedLineEditor(input_field)
        self.input_line_edit.setMinimumSize(QtCore.QSize(0, 50))
        self.input_line_edit.setObjectName("input_line_edit")
        self.verticalLayout.addWidget(self.input_line_edit)
        self.info_label = QtWidgets.QLabel(input_field)
        self.info_label.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)

        self.retranslateUi(input_field)
        QtCore.QMetaObject.connectSlotsByName(input_field)

    def retranslateUi(self, input_field):
        _translate = QtCore.QCoreApplication.translate
        input_field.setWindowTitle(_translate("input_field", "Form"))
        self.name_label.setText(_translate("input_field", "Field name"))
        self.info_label.setText(_translate("input_field", "Information"))
from validatedlineeditor import ValidatedLineEditor
