# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/login_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(382, 627)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_form.sizePolicy().hasHeightForWidth())
        login_form.setSizePolicy(sizePolicy)
        login_form.setMinimumSize(QtCore.QSize(382, 627))
        login_form.setMaximumSize(QtCore.QSize(382, 627))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/images/clear_vision_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login_form.setWindowIcon(icon)
        login_form.setWindowOpacity(9.0)
        login_form.setAutoFillBackground(False)
        login_form.setStyleSheet("background:rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(login_form)
        self.label.setGeometry(QtCore.QRect(90, 40, 191, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(191, 191))
        self.label.setMaximumSize(QtCore.QSize(191, 191))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/Icons/profile.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(login_form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 440, 286, 135))
        self.layoutWidget.setObjectName("layoutWidget")
        self.buttons_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.buttons_layout.setContentsMargins(0, 0, 0, 0)
        self.buttons_layout.setSpacing(35)
        self.buttons_layout.setObjectName("buttons_layout")
        self.login_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(284, 49))
        self.login_btn.setMaximumSize(QtCore.QSize(284, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.login_btn.setFont(font)
        self.login_btn.setAutoFillBackground(False)
        self.login_btn.setStyleSheet(" background-color: #3657FF;\n"
"  border: none;\n"
"  color: white;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"")
        self.login_btn.setFlat(False)
        self.login_btn.setObjectName("login_btn")
        self.buttons_layout.addWidget(self.login_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_btn.sizePolicy().hasHeightForWidth())
        self.cancel_btn.setSizePolicy(sizePolicy)
        self.cancel_btn.setMinimumSize(QtCore.QSize(284, 49))
        self.cancel_btn.setMaximumSize(QtCore.QSize(284, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setAutoFillBackground(False)
        self.cancel_btn.setStyleSheet(" background-color: #3657FF;\n"
"  border: none;\n"
"  color: white;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"")
        self.cancel_btn.setFlat(False)
        self.cancel_btn.setObjectName("cancel_btn")
        self.buttons_layout.addWidget(self.cancel_btn)
        self.layoutWidget1 = QtWidgets.QWidget(login_form)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 270, 286, 135))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.lineedit_layout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.lineedit_layout.setContentsMargins(0, 0, 0, 0)
        self.lineedit_layout.setSpacing(35)
        self.lineedit_layout.setObjectName("lineedit_layout")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLineEdit.sizePolicy().hasHeightForWidth())
        self.usernameLineEdit.setSizePolicy(sizePolicy)
        self.usernameLineEdit.setMinimumSize(QtCore.QSize(284, 49))
        self.usernameLineEdit.setMaximumSize(QtCore.QSize(284, 49))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.lineedit_layout.addWidget(self.usernameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit.setSizePolicy(sizePolicy)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(284, 49))
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(284, 49))
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.lineedit_layout.addWidget(self.passwordLineEdit)

        self.retranslateUi(login_form)
        self.cancel_btn.clicked.connect(login_form.close)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Form"))
        self.login_btn.setText(_translate("login_form", "Login"))
        self.cancel_btn.setText(_translate("login_form", "Cancel"))
        self.usernameLineEdit.setPlaceholderText(_translate("login_form", "User name"))
        self.passwordLineEdit.setPlaceholderText(_translate("login_form", "Password"))
import resources_rc
