# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/products_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_products_main_window(object):
    def setupUi(self, products_main_window):
        products_main_window.setObjectName("products_main_window")
        products_main_window.resize(411, 324)
        self.centralwidget = QtWidgets.QWidget(products_main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.products_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.products_btn.sizePolicy().hasHeightForWidth())
        self.products_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.products_btn.setFont(font)
        self.products_btn.setObjectName("products_btn")
        self.verticalLayout.addWidget(self.products_btn)
        self.brands_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brands_btn.sizePolicy().hasHeightForWidth())
        self.brands_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.brands_btn.setFont(font)
        self.brands_btn.setObjectName("brands_btn")
        self.verticalLayout.addWidget(self.brands_btn)
        self.categories_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categories_btn.sizePolicy().hasHeightForWidth())
        self.categories_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.categories_btn.setFont(font)
        self.categories_btn.setObjectName("categories_btn")
        self.verticalLayout.addWidget(self.categories_btn)
        products_main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(products_main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        products_main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(products_main_window)
        self.statusbar.setObjectName("statusbar")
        products_main_window.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(products_main_window)
        QtCore.QMetaObject.connectSlotsByName(products_main_window)

    def retranslateUi(self, products_main_window):
        _translate = QtCore.QCoreApplication.translate
        products_main_window.setWindowTitle(_translate("products_main_window", "MainWindow"))
        self.products_btn.setText(_translate("products_main_window", "Products"))
        self.brands_btn.setText(_translate("products_main_window", "Brands"))
        self.categories_btn.setText(_translate("products_main_window", "Categories"))
        self.menuFile.setTitle(_translate("products_main_window", "File"))
