# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/search_results.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_results(object):
    def setupUi(self, search_results):
        search_results.setObjectName("search_results")
        search_results.resize(914, 725)
        self.verticalLayout = QtWidgets.QVBoxLayout(search_results)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(search_results)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(search_results)
        QtCore.QMetaObject.connectSlotsByName(search_results)

    def retranslateUi(self, search_results):
        _translate = QtCore.QCoreApplication.translate
        search_results.setWindowTitle(_translate("search_results", "Form"))
