# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/system_properties_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_systemProperties(object):
    def setupUi(self, systemProperties):
        systemProperties.setObjectName("systemProperties")
        systemProperties.resize(399, 422)
        self.verticalLayout = QtWidgets.QVBoxLayout(systemProperties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.job_titles_btn = QtWidgets.QPushButton(systemProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_titles_btn.sizePolicy().hasHeightForWidth())
        self.job_titles_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.job_titles_btn.setFont(font)
        self.job_titles_btn.setObjectName("job_titles_btn")
        self.verticalLayout.addWidget(self.job_titles_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.groups_btn = QtWidgets.QPushButton(systemProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups_btn.sizePolicy().hasHeightForWidth())
        self.groups_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.groups_btn.setFont(font)
        self.groups_btn.setObjectName("groups_btn")
        self.verticalLayout.addWidget(self.groups_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.status_btn = QtWidgets.QPushButton(systemProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_btn.sizePolicy().hasHeightForWidth())
        self.status_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.status_btn.setFont(font)
        self.status_btn.setObjectName("status_btn")
        self.verticalLayout.addWidget(self.status_btn)

        self.retranslateUi(systemProperties)
        QtCore.QMetaObject.connectSlotsByName(systemProperties)

    def retranslateUi(self, systemProperties):
        _translate = QtCore.QCoreApplication.translate
        systemProperties.setWindowTitle(_translate("systemProperties", "Form"))
        self.job_titles_btn.setText(_translate("systemProperties", "Job titles"))
        self.groups_btn.setText(_translate("systemProperties", "User groups"))
        self.status_btn.setText(_translate("systemProperties", "Status"))
